version: "3"
services:
  server:
    build: 
      context: ..
      dockerfile: dev-server/dockerfile
    ports:
      - 3000:3000
    command: yarn dev:run:server
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    depends_on:
      - database
      - worker
  worker:
    build: 
      context: ..
      dockerfile: dev-server/dockerfile
    command: yarn dev:run:worker
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    depends_on:
      - database
  database:
    image: postgres
    volumes:
      - ./__data__:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
